-- ============================================================================
-- Pinturitas · 06.3 · Láminas (parte 3 de 4): playa, fiestas, familia, cuerpo,
-- ropa, colores, formas, números.
-- ============================================================================

insert into public.drawings (world_id, slug, name_es, name_en, phonetic_es, line_art_path, sort_order, is_active)
select w.id, d.slug, d.name_es, d.name_en, d.phonetic_es,
       'line-art/' || d.world_slug || '/' || d.slug || '.png', d.sort_order, true
from (values
  ('instruments','banjo','Banjo','Banjo','BÁN-llo',12),
  ('instruments','bongos','Bongós','Bongos','BÓN-gous',13),
  ('instruments','cello','Violonchelo','Cello','CHÉ-lou',14),
  ('instruments','cymbals','Platillos','Cymbals','SÍM-bals',15),
  ('instruments','harmonica','Armónica','Harmonica','jar-MÓ-ni-ka',16),
  ('instruments','harp','Arpa','Harp','jarp',17),
  ('instruments','ukulele','Ukelele','Ukulele','iu-ku-LÉI-li',18),
  ('instruments','recorder','Flauta dulce','Recorder','ri-KÓR-der',19),
  ('instruments','trombone','Trombón','Trombone','trom-BÓUN',20),
  ('beach','beach-ball','Pelota de playa','Beach Ball','biich bol',1),
  ('beach','beach-umbrella','Sombrilla','Beach Umbrella','biich am-BRÉ-la',2),
  ('beach','coconut-drink','Coco','Coconut Drink','KÓ-ko-nat drink',3),
  ('beach','flip-flops','Sandalias','Flip Flops','flip flops',4),
  ('beach','palm-tree','Palmera','Palm Tree','paam trii',5),
  ('beach','popsicle','Paleta','Popsicle','PÓP-si-kel',6),
  ('beach','sand-bucket','Cubeta','Sand Bucket','sand BÁ-ket',7),
  ('beach','sandcastle','Castillo de arena','Sandcastle','SÁND-ka-sel',8),
  ('beach','seashell','Concha','Seashell','SÍI-shel',9),
  ('beach','surfboard','Tabla de surf','Surfboard','SÉRF-bord',10),
  ('beach','anchor','Ancla','Anchor','ÁN-ker',11),
  ('beach','beach-towel','Toalla de playa','Beach Towel','biich TÁU-el',12),
  ('beach','life-jacket','Chaleco salvavidas','Life Jacket','láif LLÁ-ket',13),
  ('beach','lighthouse','Faro','Lighthouse','LÁIT-jaus',14),
  ('beach','sand-dollar','Dólar de arena','Sand Dollar','sand DÓ-lar',15),
  ('beach','sunglasses','Lentes de sol','Sunglasses','SÁN-gla-ses',16),
  ('beach','sunscreen','Bloqueador','Sunscreen','SÁN-skriin',17),
  ('beach','swimsuit','Traje de baño','Swimsuit','SUÍM-sut',18),
  ('beach','beach-chair','Silla de playa','Beach Chair','biich cher',19),
  ('beach','snorkel','Esnórquel','Snorkel','SNÓR-kel',20),
  ('holidays','balloon','Globo','Balloon','ba-LÚN',1),
  ('holidays','christmas-tree','Árbol de Navidad','Christmas Tree','KRÍS-mas trii',2),
  ('holidays','easter-egg','Huevo de Pascua','Easter Egg','ÍS-ter eg',3),
  ('holidays','ghost','Fantasma','Ghost','goust',4),
  ('holidays','gift','Regalo','Gift','gift',5),
  ('holidays','heart','Corazón','Heart','jart',6),
  ('holidays','party-hat','Gorro de fiesta','Party Hat','PÁR-ti jat',7),
  ('holidays','pumpkin','Calabaza','Pumpkin','PÁMP-kin',8),
  ('holidays','santa','Santa','Santa','SÁN-ta',9),
  ('holidays','snowman','Muñeco de nieve','Snowman','SNÓU-man',10),
  ('holidays','candy-cane','Bastón de dulce','Candy Cane','KÁN-di kéin',11),
  ('holidays','confetti','Confeti','Confetti','kon-FÉ-ti',12),
  ('holidays','fireworks','Fuegos artificiales','Fireworks','FÁIR-uerks',13),
  ('holidays','lantern','Farolito','Lantern','LÁN-tern',14),
  ('holidays','ornament','Esfera navideña','Ornament','ÓR-na-ment',15),
  ('holidays','piñata','Piñata','Piñata','pin-IÁ-ta',16),
  ('holidays','reindeer','Reno','Reindeer','RÉIN-diir',17),
  ('holidays','stocking','Calceta navideña','Stocking','STÓ-king',18),
  ('holidays','gingerbread-man','Galleta de jengibre','Gingerbread Man','LLÍN-ller-bred man',19),
  ('holidays','wreath','Corona navideña','Wreath','riiz',20),
  ('family','baby','Bebé','Baby','BÉI-bi',1),
  ('family','boy','Niño','Boy','boi',2),
  ('family','brother','Hermano','Brother','BRÁ-der',3),
  ('family','cousin','Primo','Cousin','KÁ-sin',4),
  ('family','dad','Papá','Dad','dad',5),
  ('family','family','Familia','Family','FÁ-mi-li',6),
  ('family','friend','Amigo','Friend','frend',7),
  ('family','girl','Niña','Girl','guerl',8),
  ('family','grandma','Abuela','Grandma','GRÁND-ma',9),
  ('family','grandpa','Abuelo','Grandpa','GRÁND-pa',10),
  ('family','sister','Hermana','Sister','SÍS-ter',11),
  ('family','toddler','Nene','Toddler','TÓD-ler',12),
  ('family','twins','Gemelos','Twins','tuins',13),
  ('family','aunt','Tía','Aunt','ant',14),
  ('family','mom','Mamá','Mom','mom',15),
  ('family','uncle','Tío','Uncle','ÁN-kel',16),
  ('body','finger','Dedo','Finger','FÍN-ger',1),
  ('body','hair','Cabello','Hair','jer',2),
  ('body','hand','Mano','Hand','jand',3),
  ('body','head','Cabeza','Head','jed',4),
  ('body','neck','Cuello','Neck','nek',5),
  ('body','nose','Nariz','Nose','nous',6),
  ('body','arm','Brazo','Arm','arm',7),
  ('body','back','Espalda','Back','bak',8),
  ('body','cheek','Mejilla','Cheek','chiik',9),
  ('body','ear','Oreja','Ear','iir',10),
  ('body','eye','Ojo','Eye','ái',11),
  ('body','foot','Pie','Foot','fut',12),
  ('body','knee','Rodilla','Knee','nii',13),
  ('body','leg','Pierna','Leg','leg',14),
  ('body','mouth','Boca','Mouth','mauz',15),
  ('body','shoulder','Hombro','Shoulder','SHÓUL-der',16),
  ('body','teeth','Dientes','Teeth','tiiz',17),
  ('body','toe','Dedo del pie','Toe','tou',18),
  ('body','tongue','Lengua','Tongue','tang',19),
  ('body','tummy','Pancita','Tummy','TÁ-mi',20),
  ('clothes','coat','Abrigo','Coat','kout',1),
  ('clothes','dress','Vestido','Dress','dres',2),
  ('clothes','gloves','Guantes','Gloves','glavs',3),
  ('clothes','hat','Sombrero','Hat','jat',4),
  ('clothes','jacket','Chaqueta','Jacket','LLÁ-ket',5),
  ('clothes','mittens','Mitones','Mittens','MÍ-tens',6),
  ('clothes','shirt','Camisa','Shirt','shert',7),
  ('clothes','shoes','Zapatos','Shoes','shus',8),
  ('clothes','skirt','Falda','Skirt','skert',9),
  ('clothes','sweater','Suéter','Sweater','SUÉ-ter',10),
  ('clothes','t-shirt','Playera','T-Shirt','TI-shert',11),
  ('clothes','belt','Cinturón','Belt','belt',12),
  ('clothes','boots','Botas','Boots','buuts',13),
  ('clothes','cap','Gorra','Cap','kap',14),
  ('clothes','pajamas','Pijama','Pajamas','pa-LLÁ-mas',15),
  ('clothes','pants','Pantalón','Pants','pants',16),
  ('clothes','sandals','Sandalias','Sandals','SÁN-dals',17),
  ('clothes','scarf','Bufanda','Scarf','skarf',18),
  ('clothes','shorts','Shorts','Shorts','shorts',19),
  ('clothes','socks','Calcetines','Socks','soks',20),
  ('colors','blue','Azul','Blue','blu',1),
  ('colors','gold','Dorado','Gold','gould',2),
  ('colors','pink','Rosa','Pink','pink',3),
  ('colors','purple','Morado','Purple','PÉR-pel',4),
  ('colors','red','Rojo','Red','red',5),
  ('colors','beige','Beige','Beige','beish',6),
  ('colors','black','Negro','Black','blak',7),
  ('colors','brown','Café','Brown','braun',8),
  ('colors','gray','Gris','Gray','gréi',9),
  ('colors','green','Verde','Green','griin',10),
  ('colors','orange','Naranja','Orange','Ó-rinll',11),
  ('colors','silver','Plateado','Silver','SÍL-ver',12),
  ('colors','turquoise','Turquesa','Turquoise','TÉR-koiz',13),
  ('colors','violet','Violeta','Violet','VÁI-o-let',14),
  ('colors','white','Blanco','White','uáit',15),
  ('colors','yellow','Amarillo','Yellow','IÉ-lou',16),
  ('shapes','arrow','Flecha','Arrow','É-rou',1),
  ('shapes','circle','Círculo','Circle','SÉR-kel',2),
  ('shapes','cone','Cono','Cone','koun',3),
  ('shapes','cylinder','Cilindro','Cylinder','SÍ-lin-der',4),
  ('shapes','oval','Óvalo','Oval','ÓU-val',5),
  ('shapes','rectangle','Rectángulo','Rectangle','rek-TÁN-gol',6),
  ('shapes','triangle','Triángulo','Triangle','TRÁI-an-gol',7),
  ('shapes','cube','Cubo','Cube','kiub',8),
  ('shapes','diamond','Rombo','Diamond','DÁI-mond',9),
  ('shapes','hexagon','Hexágono','Hexagon','JÉK-sa-gon',10),
  ('shapes','octagon','Octágono','Octagon','ÓK-ta-gon',11),
  ('shapes','pentagon','Pentágono','Pentagon','PÉN-ta-gon',12),
  ('shapes','pyramid','Pirámide','Pyramid','PÍ-ra-mid',13),
  ('shapes','sphere','Esfera','Sphere','sfiir',14),
  ('shapes','square','Cuadrado','Square','skuér',15),
  ('numbers','one','Uno','One','uán',1),
  ('numbers','two','Dos','Two','tu',2),
  ('numbers','three','Tres','Three','zrii',3),
  ('numbers','four','Cuatro','Four','for',4),
  ('numbers','five','Cinco','Five','fáiv',5),
  ('numbers','six','Seis','Six','siks',6),
  ('numbers','seven','Siete','Seven','SÉ-ven',7),
  ('numbers','eight','Ocho','Eight','éit',8),
  ('numbers','nine','Nueve','Nine','náin',9),
  ('numbers','ten','Diez','Ten','ten',10),
  ('numbers','eleven','Once','Eleven','i-LÉ-ven',11),
  ('numbers','twelve','Doce','Twelve','tuelv',12),
  ('numbers','thirteen','Trece','Thirteen','zer-TÍN',13),
  ('numbers','fourteen','Catorce','Fourteen','for-TÍN',14),
  ('numbers','fifteen','Quince','Fifteen','fif-TÍN',15),
  ('numbers','sixteen','Dieciséis','Sixteen','siks-TÍN',16),
  ('numbers','seventeen','Diecisiete','Seventeen','se-ven-TÍN',17),
  ('numbers','eighteen','Dieciocho','Eighteen','ei-TÍN',18),
  ('numbers','nineteen','Diecinueve','Nineteen','náin-TÍN',19),
  ('numbers','twenty','Veinte','Twenty','TUÉN-ti',20),
  ('home','bathtub','Tina','Bathtub','BÁZ-tab',1),
  ('home','bed','Cama','Bed','bed',2),
  ('home','chair','Silla','Chair','cher',3),
  ('home','clock','Reloj','Clock','klok',4)
) as d(world_slug, slug, name_es, name_en, phonetic_es, sort_order)
join public.worlds w on w.slug = d.world_slug
on conflict (world_id, slug) do update set
  name_es = excluded.name_es, name_en = excluded.name_en,
  phonetic_es = excluded.phonetic_es, line_art_path = excluded.line_art_path,
  sort_order = excluded.sort_order, is_active = true;
