/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PerfilNinoRouteImport } from './routes/perfil-nino'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHotmartRouteImport } from './routes/api/hotmart'
import { Route as AppPadresRouteImport } from './routes/_app/padres'
import { Route as AppMundosRouteImport } from './routes/_app/mundos'
import { Route as AppJuegosRouteImport } from './routes/_app/juegos'
import { Route as AppHoyRouteImport } from './routes/_app/hoy'
import { Route as AppGaleriaRouteImport } from './routes/_app/galeria'
import { Route as AppPadresIndexRouteImport } from './routes/_app/padres.index'
import { Route as AppMundosIndexRouteImport } from './routes/_app/mundos.index'
import { Route as ApiPublicSendEmailRouteImport } from './routes/api/public/send-email'
import { Route as ApiPublicPaymentWebhookRouteImport } from './routes/api/public/payment-webhook'
import { Route as AppPadresProgresoRouteImport } from './routes/_app/padres.progreso'
import { Route as AppPadresPlanesRouteImport } from './routes/_app/padres.planes'
import { Route as AppPadresAjustesRouteImport } from './routes/_app/padres.ajustes'
import { Route as AppMundosWorldSlugRouteImport } from './routes/_app/mundos.$worldSlug'
import { Route as AppColoreoDrawingSlugRouteImport } from './routes/_app/coloreo.$drawingSlug'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilNinoRoute = PerfilNinoRouteImport.update({
  id: '/perfil-nino',
  path: '/perfil-nino',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotmartRoute = ApiHotmartRouteImport.update({
  id: '/api/hotmart',
  path: '/api/hotmart',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPadresRoute = AppPadresRouteImport.update({
  id: '/padres',
  path: '/padres',
  getParentRoute: () => AppRoute,
} as any)
const AppMundosRoute = AppMundosRouteImport.update({
  id: '/mundos',
  path: '/mundos',
  getParentRoute: () => AppRoute,
} as any)
const AppJuegosRoute = AppJuegosRouteImport.update({
  id: '/juegos',
  path: '/juegos',
  getParentRoute: () => AppRoute,
} as any)
const AppHoyRoute = AppHoyRouteImport.update({
  id: '/hoy',
  path: '/hoy',
  getParentRoute: () => AppRoute,
} as any)
const AppGaleriaRoute = AppGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => AppRoute,
} as any)
const AppPadresIndexRoute = AppPadresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPadresRoute,
} as any)
const AppMundosIndexRoute = AppMundosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMundosRoute,
} as any)
const ApiPublicSendEmailRoute = ApiPublicSendEmailRouteImport.update({
  id: '/api/public/send-email',
  path: '/api/public/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentWebhookRoute = ApiPublicPaymentWebhookRouteImport.update({
  id: '/api/public/payment-webhook',
  path: '/api/public/payment-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPadresProgresoRoute = AppPadresProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => AppPadresRoute,
} as any)
const AppPadresPlanesRoute = AppPadresPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => AppPadresRoute,
} as any)
const AppPadresAjustesRoute = AppPadresAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AppPadresRoute,
} as any)
const AppMundosWorldSlugRoute = AppMundosWorldSlugRouteImport.update({
  id: '/$worldSlug',
  path: '/$worldSlug',
  getParentRoute: () => AppMundosRoute,
} as any)
const AppColoreoDrawingSlugRoute = AppColoreoDrawingSlugRouteImport.update({
  id: '/coloreo/$drawingSlug',
  path: '/coloreo/$drawingSlug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil-nino': typeof PerfilNinoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/galeria': typeof AppGaleriaRoute
  '/hoy': typeof AppHoyRoute
  '/juegos': typeof AppJuegosRoute
  '/mundos': typeof AppMundosRouteWithChildren
  '/padres': typeof AppPadresRouteWithChildren
  '/api/hotmart': typeof ApiHotmartRoute
  '/coloreo/$drawingSlug': typeof AppColoreoDrawingSlugRoute
  '/mundos/$worldSlug': typeof AppMundosWorldSlugRoute
  '/padres/ajustes': typeof AppPadresAjustesRoute
  '/padres/planes': typeof AppPadresPlanesRoute
  '/padres/progreso': typeof AppPadresProgresoRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/send-email': typeof ApiPublicSendEmailRoute
  '/mundos/': typeof AppMundosIndexRoute
  '/padres/': typeof AppPadresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil-nino': typeof PerfilNinoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/galeria': typeof AppGaleriaRoute
  '/hoy': typeof AppHoyRoute
  '/juegos': typeof AppJuegosRoute
  '/api/hotmart': typeof ApiHotmartRoute
  '/coloreo/$drawingSlug': typeof AppColoreoDrawingSlugRoute
  '/mundos/$worldSlug': typeof AppMundosWorldSlugRoute
  '/padres/ajustes': typeof AppPadresAjustesRoute
  '/padres/planes': typeof AppPadresPlanesRoute
  '/padres/progreso': typeof AppPadresProgresoRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/send-email': typeof ApiPublicSendEmailRoute
  '/mundos': typeof AppMundosIndexRoute
  '/padres': typeof AppPadresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil-nino': typeof PerfilNinoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/galeria': typeof AppGaleriaRoute
  '/_app/hoy': typeof AppHoyRoute
  '/_app/juegos': typeof AppJuegosRoute
  '/_app/mundos': typeof AppMundosRouteWithChildren
  '/_app/padres': typeof AppPadresRouteWithChildren
  '/api/hotmart': typeof ApiHotmartRoute
  '/_app/coloreo/$drawingSlug': typeof AppColoreoDrawingSlugRoute
  '/_app/mundos/$worldSlug': typeof AppMundosWorldSlugRoute
  '/_app/padres/ajustes': typeof AppPadresAjustesRoute
  '/_app/padres/planes': typeof AppPadresPlanesRoute
  '/_app/padres/progreso': typeof AppPadresProgresoRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/send-email': typeof ApiPublicSendEmailRoute
  '/_app/mundos/': typeof AppMundosIndexRoute
  '/_app/padres/': typeof AppPadresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/perfil-nino'
    | '/reset-password'
    | '/galeria'
    | '/hoy'
    | '/juegos'
    | '/mundos'
    | '/padres'
    | '/api/hotmart'
    | '/coloreo/$drawingSlug'
    | '/mundos/$worldSlug'
    | '/padres/ajustes'
    | '/padres/planes'
    | '/padres/progreso'
    | '/api/public/payment-webhook'
    | '/api/public/send-email'
    | '/mundos/'
    | '/padres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/perfil-nino'
    | '/reset-password'
    | '/galeria'
    | '/hoy'
    | '/juegos'
    | '/api/hotmart'
    | '/coloreo/$drawingSlug'
    | '/mundos/$worldSlug'
    | '/padres/ajustes'
    | '/padres/planes'
    | '/padres/progreso'
    | '/api/public/payment-webhook'
    | '/api/public/send-email'
    | '/mundos'
    | '/padres'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/perfil-nino'
    | '/reset-password'
    | '/_app/galeria'
    | '/_app/hoy'
    | '/_app/juegos'
    | '/_app/mundos'
    | '/_app/padres'
    | '/api/hotmart'
    | '/_app/coloreo/$drawingSlug'
    | '/_app/mundos/$worldSlug'
    | '/_app/padres/ajustes'
    | '/_app/padres/planes'
    | '/_app/padres/progreso'
    | '/api/public/payment-webhook'
    | '/api/public/send-email'
    | '/_app/mundos/'
    | '/_app/padres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilNinoRoute: typeof PerfilNinoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiHotmartRoute: typeof ApiHotmartRoute
  ApiPublicPaymentWebhookRoute: typeof ApiPublicPaymentWebhookRoute
  ApiPublicSendEmailRoute: typeof ApiPublicSendEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-nino': {
      id: '/perfil-nino'
      path: '/perfil-nino'
      fullPath: '/perfil-nino'
      preLoaderRoute: typeof PerfilNinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotmart': {
      id: '/api/hotmart'
      path: '/api/hotmart'
      fullPath: '/api/hotmart'
      preLoaderRoute: typeof ApiHotmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/padres': {
      id: '/_app/padres'
      path: '/padres'
      fullPath: '/padres'
      preLoaderRoute: typeof AppPadresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mundos': {
      id: '/_app/mundos'
      path: '/mundos'
      fullPath: '/mundos'
      preLoaderRoute: typeof AppMundosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/juegos': {
      id: '/_app/juegos'
      path: '/juegos'
      fullPath: '/juegos'
      preLoaderRoute: typeof AppJuegosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hoy': {
      id: '/_app/hoy'
      path: '/hoy'
      fullPath: '/hoy'
      preLoaderRoute: typeof AppHoyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/galeria': {
      id: '/_app/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof AppGaleriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/padres/': {
      id: '/_app/padres/'
      path: '/'
      fullPath: '/padres/'
      preLoaderRoute: typeof AppPadresIndexRouteImport
      parentRoute: typeof AppPadresRoute
    }
    '/_app/mundos/': {
      id: '/_app/mundos/'
      path: '/'
      fullPath: '/mundos/'
      preLoaderRoute: typeof AppMundosIndexRouteImport
      parentRoute: typeof AppMundosRoute
    }
    '/api/public/send-email': {
      id: '/api/public/send-email'
      path: '/api/public/send-email'
      fullPath: '/api/public/send-email'
      preLoaderRoute: typeof ApiPublicSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-webhook': {
      id: '/api/public/payment-webhook'
      path: '/api/public/payment-webhook'
      fullPath: '/api/public/payment-webhook'
      preLoaderRoute: typeof ApiPublicPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/padres/progreso': {
      id: '/_app/padres/progreso'
      path: '/progreso'
      fullPath: '/padres/progreso'
      preLoaderRoute: typeof AppPadresProgresoRouteImport
      parentRoute: typeof AppPadresRoute
    }
    '/_app/padres/planes': {
      id: '/_app/padres/planes'
      path: '/planes'
      fullPath: '/padres/planes'
      preLoaderRoute: typeof AppPadresPlanesRouteImport
      parentRoute: typeof AppPadresRoute
    }
    '/_app/padres/ajustes': {
      id: '/_app/padres/ajustes'
      path: '/ajustes'
      fullPath: '/padres/ajustes'
      preLoaderRoute: typeof AppPadresAjustesRouteImport
      parentRoute: typeof AppPadresRoute
    }
    '/_app/mundos/$worldSlug': {
      id: '/_app/mundos/$worldSlug'
      path: '/$worldSlug'
      fullPath: '/mundos/$worldSlug'
      preLoaderRoute: typeof AppMundosWorldSlugRouteImport
      parentRoute: typeof AppMundosRoute
    }
    '/_app/coloreo/$drawingSlug': {
      id: '/_app/coloreo/$drawingSlug'
      path: '/coloreo/$drawingSlug'
      fullPath: '/coloreo/$drawingSlug'
      preLoaderRoute: typeof AppColoreoDrawingSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppMundosRouteChildren {
  AppMundosWorldSlugRoute: typeof AppMundosWorldSlugRoute
  AppMundosIndexRoute: typeof AppMundosIndexRoute
}

const AppMundosRouteChildren: AppMundosRouteChildren = {
  AppMundosWorldSlugRoute: AppMundosWorldSlugRoute,
  AppMundosIndexRoute: AppMundosIndexRoute,
}

const AppMundosRouteWithChildren = AppMundosRoute._addFileChildren(
  AppMundosRouteChildren,
)

interface AppPadresRouteChildren {
  AppPadresAjustesRoute: typeof AppPadresAjustesRoute
  AppPadresPlanesRoute: typeof AppPadresPlanesRoute
  AppPadresProgresoRoute: typeof AppPadresProgresoRoute
  AppPadresIndexRoute: typeof AppPadresIndexRoute
}

const AppPadresRouteChildren: AppPadresRouteChildren = {
  AppPadresAjustesRoute: AppPadresAjustesRoute,
  AppPadresPlanesRoute: AppPadresPlanesRoute,
  AppPadresProgresoRoute: AppPadresProgresoRoute,
  AppPadresIndexRoute: AppPadresIndexRoute,
}

const AppPadresRouteWithChildren = AppPadresRoute._addFileChildren(
  AppPadresRouteChildren,
)

interface AppRouteChildren {
  AppGaleriaRoute: typeof AppGaleriaRoute
  AppHoyRoute: typeof AppHoyRoute
  AppJuegosRoute: typeof AppJuegosRoute
  AppMundosRoute: typeof AppMundosRouteWithChildren
  AppPadresRoute: typeof AppPadresRouteWithChildren
  AppColoreoDrawingSlugRoute: typeof AppColoreoDrawingSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGaleriaRoute: AppGaleriaRoute,
  AppHoyRoute: AppHoyRoute,
  AppJuegosRoute: AppJuegosRoute,
  AppMundosRoute: AppMundosRouteWithChildren,
  AppPadresRoute: AppPadresRouteWithChildren,
  AppColoreoDrawingSlugRoute: AppColoreoDrawingSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilNinoRoute: PerfilNinoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiHotmartRoute: ApiHotmartRoute,
  ApiPublicPaymentWebhookRoute: ApiPublicPaymentWebhookRoute,
  ApiPublicSendEmailRoute: ApiPublicSendEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
