insert into public.drawings (world_id, slug, name_es, name_en, phonetic_es, line_art_path, sort_order, is_active)
select w.id, d.slug, d.name_es, d.name_en, d.phonetic_es,
       'line-art/' || d.world_slug || '/' || d.slug || '.png', d.sort_order, true
from (values
  ('vehicles','ambulance','Ambulancia','Ambulance','ÁM-biu-lans',11),
  ('vehicles','boat','Bote','Boat','bout',12),
  ('vehicles','crane','Grúa','Crane','kréin',13),
  ('vehicles','excavator','Excavadora','Excavator','ÉKS-ka-vei-tor',14),
  ('vehicles','motorcycle','Motocicleta','Motorcycle','MÓU-tor-sai-kel',15),
  ('vehicles','scooter','Scooter','Scooter','SKÚ-ter',16),
  ('vehicles','submarine','Submarino','Submarine','SÁB-ma-rin',17),
  ('vehicles','van','Camioneta','Van','van',18),
  ('vehicles','hot-air-balloon','Globo aerostático','Hot Air Balloon','jot er ba-LÚN',19),
  ('vehicles','taxi','Taxi','Taxi','TÁK-si',20),
  ('space','alien','Extraterrestre','Alien','ÉI-lien',1),
  ('space','astronaut','Astronauta','Astronaut','ÁS-tro-not',2),
  ('space','comet','Cometa','Comet','KÓ-met',3),
  ('space','moon','Luna','Moon','mun',4),
  ('space','planet','Planeta','Planet','PLÁ-net',5),
  ('space','rocket','Cohete','Rocket','RÓ-ket',6),
  ('space','saturn','Saturno','Saturn','SÁ-turn',7),
  ('space','star','Estrella','Star','star',8),
  ('space','sun','Sol','Sun','san',9),
  ('space','ufo','Platillo volador','UFO','iu-ef-ÓU',10),
  ('space','earth','La Tierra','Earth','erz',11),
  ('space','galaxy','Galaxia','Galaxy','GÁ-lak-si',12),
  ('space','jupiter','Júpiter','Jupiter','LLÚ-pi-ter',13),
  ('space','mars','Marte','Mars','mars',14),
  ('space','nebula','Nebulosa','Nebula','NÉ-biu-la',15),
  ('space','satellite','Satélite','Satellite','SÁ-te-lait',16),
  ('space','space-rover','Explorador espacial','Space Rover','spéis RÓU-ver',17),
  ('space','space-station','Estación espacial','Space Station','spéis STÉI-shon',18),
  ('space','meteor','Meteoro','Meteor','MÍI-tior',19),
  ('space','telescope','Telescopio','Telescope','TÉ-les-koup',20),
  ('princesses-castle','baby-dragon','Dragón bebé','Baby Dragon','BÉI-bi DRÁ-gon',1),
  ('princesses-castle','castle','Castillo','Castle','KÁ-sel',2),
  ('princesses-castle','crown','Corona','Crown','kraun',3),
  ('princesses-castle','fairy','Hada','Fairy','FÉ-ri',4),
  ('princesses-castle','king','Rey','King','king',5),
  ('princesses-castle','prince','Príncipe','Prince','prins',6),
  ('princesses-castle','princess','Princesa','Princess','PRÍN-ses',7),
  ('princesses-castle','queen','Reina','Queen','kuiin',8),
  ('princesses-castle','unicorn','Unicornio','Unicorn','IÚ-ni-korn',9),
  ('princesses-castle','wizard','Mago','Wizard','UÍ-sard',10),
  ('princesses-castle','dragon','Dragón','Dragon','DRÁ-gon',11),
  ('princesses-castle','genie','Genio','Genie','LLÍ-ni',12),
  ('princesses-castle','knight','Caballero','Knight','náit',13),
  ('princesses-castle','magic-book','Libro mágico','Magic Book','MÁ-llik buk',14),
  ('princesses-castle','magic-wand','Varita mágica','Magic Wand','MÁ-llik uónd',15),
  ('princesses-castle','mermaid','Sirena','Mermaid','MÉR-meid',16),
  ('princesses-castle','pegasus','Pegaso','Pegasus','PÉ-ga-sus',17),
  ('princesses-castle','throne','Trono','Throne','zroun',18),
  ('princesses-castle','treasure-chest','Cofre del tesoro','Treasure Chest','TRÉ-sher chest',19),
  ('princesses-castle','witch','Bruja','Witch','uich',20),
  ('food','cake','Pastel','Cake','kéik',3),
  ('food','cookie','Galleta','Cookie','KÚ-ki',5),
  ('food','cupcake','Panquecito','Cupcake','KÁP-keik',6),
  ('food','ice-cream','Helado','Ice Cream','áis kriim',7),
  ('food','pizza','Pizza','Pizza','PÍT-sa',8),
  ('food','bread','Pan','Bread','bred',9),
  ('food','candy','Dulce','Candy','KÁN-di',10),
  ('food','cheese','Queso','Cheese','chiis',11),
  ('food','donut','Dona','Donut','DÓU-nat',12),
  ('food','french-fries','Papas fritas','French Fries','french fráis',13),
  ('food','hamburger','Hamburguesa','Hamburger','JÁM-ber-ger',14),
  ('food','hot-dog','Hot dog','Hot Dog','jot dog',15),
  ('food','pancake','Panqueque','Pancake','PÁN-keik',16),
  ('food','popcorn','Palomitas','Popcorn','PÓP-korn',17),
  ('food','soup','Sopa','Soup','sup',18),
  ('food','spaghetti','Espagueti','Spaghetti','spa-GÉ-ti',19),
  ('food','taco','Taco','Taco','TÁ-kou',20),
  ('food','egg','Huevo','Egg','eg',21),
  ('food','pie','Tarta','Pie','pái',22),
  ('food','sandwich','Sándwich','Sandwich','SÁND-uich',23),
  ('fruits','apple','Manzana','Apple','Á-pel',1),
  ('fruits','banana','Plátano','Banana','ba-NÁ-na',2),
  ('fruits','strawberry','Fresa','Strawberry','STRÓ-be-ri',9),
  ('fruits','watermelon','Sandía','Watermelon','UÓ-ter-me-lon',10),
  ('fruits','blueberry','Arándano','Blueberry','BLÚ-be-ri',11),
  ('fruits','cherry','Cereza','Cherry','CHÉ-ri',12),
  ('fruits','coconut','Coco','Coconut','KÓ-ko-nat',13),
  ('fruits','fig','Higo','Fig','fig',14),
  ('fruits','melon','Melón','Melon','MÉ-lon',15),
  ('fruits','peach','Durazno','Peach','piich',16),
  ('fruits','pear','Pera','Pear','per',17),
  ('fruits','plum','Ciruela','Plum','plam',18),
  ('fruits','raspberry','Frambuesa','Raspberry','RÁS-be-ri',19),
  ('fruits','tangerine','Mandarina','Tangerine','tan-lle-RÍN',20),
  ('fruits','grapefruit','Toronja','Grapefruit','GRÉIP-frut',21),
  ('fruits','grapes','Uvas','Grapes','gréips',22),
  ('fruits','kiwi','Kiwi','Kiwi','KÍ-ui',23),
  ('fruits','lemon','Limón','Lemon','LÉ-mon',24),
  ('fruits','mango','Mango','Mango','MÁN-gou',25),
  ('fruits','pineapple','Piña','Pineapple','PÁIN-a-pel',26),
  ('vegetables','carrot','Zanahoria','Carrot','KÉ-rot',4),
  ('vegetables','beet','Betabel','Beet','biit',5),
  ('vegetables','corn','Elote','Corn','korn',6),
  ('vegetables','eggplant','Berenjena','Eggplant','ÉG-plant',7),
  ('vegetables','garlic','Ajo','Garlic','GÁR-lik',8),
  ('vegetables','mushroom','Champiñón','Mushroom','MÁSH-rum',9),
  ('vegetables','onion','Cebolla','Onion','Á-nion',10),
  ('vegetables','pea','Chícharo','Pea','pii',11),
  ('vegetables','pepper','Pimiento','Pepper','PÉ-per',12),
  ('vegetables','broccoli','Brócoli','Broccoli','BRÓ-co-li',13),
  ('vegetables','cabbage','Repollo','Cabbage','KÁ-bill',14),
  ('vegetables','cauliflower','Coliflor','Cauliflower','KÓ-li-flau-er',15),
  ('vegetables','celery','Apio','Celery','SÉ-le-ri',16),
  ('vegetables','cucumber','Pepino','Cucumber','KIÚ-kam-ber',17),
  ('vegetables','lettuce','Lechuga','Lettuce','LÉ-tus',18),
  ('vegetables','potato','Papa','Potato','po-TÉI-tou',19),
  ('vegetables','radish','Rábano','Radish','RÁ-dish',20),
  ('vegetables','spinach','Espinaca','Spinach','SPÍ-nich',21),
  ('vegetables','tomato','Tomate','Tomato','to-MÉI-tou',22),
  ('sports','basketball','Básquetbol','Basketball','BÁS-ket-bol',1),
  ('sports','bicycle','Bicicleta','Bicycle','BÁI-si-kel',2),
  ('sports','jump-rope','Cuerda','Jump Rope','llamp roup',3),
  ('sports','kite','Papalote','Kite','káit',4),
  ('sports','medal','Medalla','Medal','MÉ-dal',5),
  ('sports','roller-skate','Patines','Roller Skate','RÓU-ler skéit',6),
  ('sports','skateboard','Patineta','Skateboard','SKÉIT-bord',7),
  ('sports','soccer-ball','Balón','Soccer Ball','SÓ-ker bol',8),
  ('sports','tennis','Tenis','Tennis','TÉ-nis',9),
  ('sports','trophy','Trofeo','Trophy','TRÓU-fi',10),
  ('sports','bowling','Boliche','Bowling','BÓU-ling',11),
  ('sports','boxing-gloves','Guantes de box','Boxing Gloves','BÓK-sing glavs',12),
  ('sports','football','Fútbol americano','Football','FÚT-bol',13),
  ('sports','golf','Golf','Golf','golf',14),
  ('sports','ice-skates','Patines de hielo','Ice Skates','áis skéits',15),
  ('sports','skis','Esquís','Skis','skiis',16),
  ('sports','volleyball','Voleibol','Volleyball','VÓ-li-bol',17),
  ('sports','baseball','Béisbol','Baseball','BÉIS-bol',18),
  ('sports','baseball-bat','Bate','Baseball Bat','BÉIS-bol bat',19),
  ('sports','hockey-stick','Palo de hockey','Hockey Stick','JÓ-ki stik',20),
  ('jobs','chef','Cocinero','Chef','shef',1),
  ('jobs','doctor','Doctor','Doctor','DÓK-tor',2),
  ('jobs','farmer','Granjero','Farmer','FÁR-mer',3),
  ('jobs','firefighter','Bombero','Firefighter','FÁIR-fai-ter',4),
  ('jobs','nurse','Enfermera','Nurse','ners',5),
  ('jobs','painter','Pintor','Painter','PÉIN-ter',6),
  ('jobs','pilot','Piloto','Pilot','PÁI-lot',7),
  ('jobs','police-officer','Policía','Police Officer','po-LÍS Ó-fi-ser',8),
  ('jobs','teacher','Maestro','Teacher','TÍI-cher',9),
  ('jobs','vet','Veterinario','Vet','vet',10),
  ('jobs','barber','Barbero','Barber','BÁR-ber',11),
  ('jobs','carpenter','Carpintero','Carpenter','KÁR-pen-ter',12),
  ('jobs','dentist','Dentista','Dentist','DÉN-tist',13),
  ('jobs','fisherman','Pescador','Fisherman','FÍ-sher-man',14),
  ('jobs','mailman','Cartero','Mailman','MÉIL-man',15),
  ('jobs','scientist','Científico','Scientist','SÁIN-tist',16),
  ('jobs','waiter','Mesero','Waiter','UÉI-ter',17),
  ('jobs','ballerina','Bailarina','Ballerina','ba-le-RÍ-na',18),
  ('jobs','clown','Payaso','Clown','klaun',19),
  ('jobs','plumber','Plomero','Plumber','PLÁ-mer',20),
  ('instruments','drum','Tambor','Drum','dram',1),
  ('instruments','flute','Flauta','Flute','fluut',2),
  ('instruments','guitar','Guitarra','Guitar','gui-TÁR',3),
  ('instruments','maracas','Maracas','Maracas','ma-RÁ-kas',4),
  ('instruments','piano','Piano','Piano','PIÁ-nou',5),
  ('instruments','saxophone','Saxofón','Saxophone','SÁK-so-foun',6),
  ('instruments','tambourine','Pandereta','Tambourine','tam-bu-RÍN',7),
  ('instruments','trumpet','Trompeta','Trumpet','TRÁM-pet',8),
  ('instruments','violin','Violín','Violin','vai-o-LÍN',9),
  ('instruments','xylophone','Xilófono','Xylophone','SÁI-lo-foun',10),
  ('instruments','accordion','Acordeón','Accordion','a-KÓR-di-on',11)
) as d(world_slug, slug, name_es, name_en, phonetic_es, sort_order)
join public.worlds w on w.slug = d.world_slug
on conflict (world_id, slug) do update set
  name_es = excluded.name_es, name_en = excluded.name_en,
  phonetic_es = excluded.phonetic_es, line_art_path = excluded.line_art_path,
  sort_order = excluded.sort_order, is_active = true;