insert into public.drawings (world_id, slug, name_es, name_en, phonetic_es, line_art_path, sort_order, is_active)
select w.id, d.slug, d.name_es, d.name_en, d.phonetic_es,
       'line-art/' || d.world_slug || '/' || d.slug || '.png', d.sort_order, true
from (values
  ('pets','dog','Perro','Dog','dog',1),
  ('pets','cat','Gato','Cat','kat',2),
  ('pets','rabbit','Conejo','Rabbit','RÁ-bit',3),
  ('pets','goldfish','Pez dorado','Goldfish','GÓLD-fish',4),
  ('pets','hamster','Hámster','Hamster','JÁMS-ter',5),
  ('pets','turtle','Tortuga','Turtle','TÉR-tel',6),
  ('pets','parakeet','Periquito','Parakeet','PÁ-ra-kit',7),
  ('pets','canary','Canario','Canary','ka-NÉ-ri',8),
  ('pets','chinchilla','Chinchilla','Chinchilla','chin-CHÍ-la',9),
  ('pets','ferret','Hurón','Ferret','FÉ-ret',10),
  ('pets','gecko','Geco','Gecko','GÉ-kou',11),
  ('pets','guinea-pig','Cobayo','Guinea Pig','GUÍ-ni pig',12),
  ('pets','kitten','Gatito','Kitten','KÍ-ten',13),
  ('pets','mouse','Ratón','Mouse','maus',14),
  ('pets','puppy','Perrito','Puppy','PÁ-pi',15),
  ('pets','cockatiel','Cacatúa','Cockatiel','ko-ka-TÍL',16),
  ('pets','frog','Rana','Frog','frog',17),
  ('pets','hermit-crab','Cangrejo ermitaño','Hermit Crab','JÉR-mit krab',18),
  ('pets','snake','Serpiente','Snake','snéik',19),
  ('pets','tortoise','Tortuga terrestre','Tortoise','TÓR-tes',20),
  ('farm','cow','Vaca','Cow','káu',1),
  ('farm','pig','Cerdo','Pig','pig',2),
  ('farm','horse','Caballo','Horse','jors',3),
  ('farm','hen','Gallina','Hen','jen',4),
  ('farm','duck','Pato','Duck','dak',5),
  ('farm','sheep','Oveja','Sheep','shiip',6),
  ('farm','rooster','Gallo','Rooster','RÚS-ter',7),
  ('farm','bull','Toro','Bull','bul',8),
  ('farm','donkey','Burro','Donkey','DÓN-ki',9),
  ('farm','foal','Potro','Foal','foul',10),
  ('farm','goat','Cabra','Goat','gout',11),
  ('farm','goose','Ganso','Goose','guus',12),
  ('farm','lamb','Cordero','Lamb','lam',13),
  ('farm','llama','Llama','Llama','LLÁ-ma',14),
  ('farm','turkey','Pavo','Turkey','TÉR-ki',15),
  ('farm','alpaca','Alpaca','Alpaca','al-PÁ-ka',16),
  ('farm','calf','Ternero','Calf','kaf',17),
  ('farm','chick','Pollito','Chick','chik',18),
  ('farm','piglet','Cerdito','Piglet','PÍG-let',19),
  ('farm','pony','Poni','Pony','PÓU-ni',20),
  ('wild','lion','León','Lion','LÁI-on',1),
  ('wild','tiger','Tigre','Tiger','TÁI-ger',2),
  ('wild','elephant','Elefante','Elephant','É-le-fant',3),
  ('wild','zebra','Cebra','Zebra','ZÍ-bra',4),
  ('wild','giraffe','Jirafa','Giraffe','lli-RAF',5),
  ('wild','hippo','Hipopótamo','Hippo','JÍ-po',6),
  ('wild','rhinoceros','Rinoceronte','Rhinoceros','rai-NÓ-se-ros',7),
  ('wild','camel','Camello','Camel','KÁ-mel',8),
  ('wild','cheetah','Guepardo','Cheetah','CHÍI-ta',9),
  ('wild','crocodile','Cocodrilo','Crocodile','KRÓ-ko-dail',10),
  ('wild','gorilla','Gorila','Gorilla','go-RÍ-la',11),
  ('wild','kangaroo','Canguro','Kangaroo','kan-ga-RÚ',12),
  ('wild','koala','Koala','Koala','ko-Á-la',13),
  ('wild','leopard','Leopardo','Leopard','LÉ-pard',14),
  ('wild','monkey','Mono','Monkey','MÁN-ki',15),
  ('wild','panda','Panda','Panda','PÁN-da',16),
  ('wild','sloth','Perezoso','Sloth','sloz',17),
  ('wild','antelope','Antílope','Antelope','ÁN-te-loup',18),
  ('wild','buffalo','Búfalo','Buffalo','BÁ-fa-lou',19),
  ('wild','lemur','Lémur','Lemur','LÍI-mer',20),
  ('forest','fox','Zorro','Fox','foks',1),
  ('forest','deer','Ciervo','Deer','diir',2),
  ('forest','wolf','Lobo','Wolf','wulf',3),
  ('forest','owl','Búho','Owl','ául',4),
  ('forest','squirrel','Ardilla','Squirrel','SKUÉ-rel',5),
  ('forest','raccoon','Mapache','Raccoon','ra-KÚN',6),
  ('forest','bear','Oso','Bear','ber',7),
  ('forest','badger','Tejón','Badger','BÁ-ller',8),
  ('forest','beaver','Castor','Beaver','BÍI-ver',9),
  ('forest','boar','Jabalí','Boar','bor',10),
  ('forest','chipmunk','Ardilla listada','Chipmunk','CHÍP-mank',11),
  ('forest','hedgehog','Erizo','Hedgehog','JÉLL-jog',12),
  ('forest','mole','Topo','Mole','moul',13),
  ('forest','moose','Alce','Moose','mus',14),
  ('forest','skunk','Zorrillo','Skunk','skank',15),
  ('forest','lynx','Lince','Lynx','links',16),
  ('forest','otter','Nutria','Otter','Ó-ter',17),
  ('forest','porcupine','Puercoespín','Porcupine','PÓR-kiu-pain',18),
  ('forest','salamander','Salamandra','Salamander','SÁ-la-man-der',19),
  ('forest','weasel','Comadreja','Weasel','UÍI-sel',20),
  ('ocean','dolphin','Delfín','Dolphin','DÓL-fin',1),
  ('ocean','shark','Tiburón','Shark','shark',2),
  ('ocean','octopus','Pulpo','Octopus','ÓK-to-pus',3),
  ('ocean','whale','Ballena','Whale','wéil',4),
  ('ocean','starfish','Estrella de mar','Starfish','STÁR-fish',5),
  ('ocean','seahorse','Caballito de mar','Seahorse','SÍ-jors',6),
  ('ocean','jellyfish','Medusa','Jellyfish','LLÉ-li-fish',7),
  ('ocean','clownfish','Pez payaso','Clownfish','KLÁUN-fish',8),
  ('ocean','crab','Cangrejo','Crab','krab',9),
  ('ocean','lobster','Langosta','Lobster','LÓBS-ter',10),
  ('ocean','narwhal','Narval','Narwhal','NÁR-ual',11),
  ('ocean','orca','Orca','Orca','ÓR-ka',12),
  ('ocean','penguin','Pingüino','Penguin','PÉN-guin',13),
  ('ocean','seal','Foca','Seal','siil',14),
  ('ocean','shrimp','Camarón','Shrimp','shrimp',15),
  ('ocean','stingray','Raya','Stingray','STÍN-grei',16),
  ('ocean','walrus','Morsa','Walrus','UÓL-rus',17),
  ('ocean','eel','Anguila','Eel','iil',18),
  ('ocean','sea-turtle','Tortuga marina','Sea Turtle','sii TÉR-tel',19),
  ('ocean','swordfish','Pez espada','Swordfish','SÓRD-fish',20),
  ('flying','eagle','Águila','Eagle','Í-gol',1),
  ('flying','falcon','Halcón','Falcon','FÁL-kon',2),
  ('flying','parrot','Loro','Parrot','PÉ-rot',3),
  ('flying','hummingbird','Colibrí','Hummingbird','JÁ-ming-berd',4),
  ('flying','bat','Murciélago','Bat','bat',5),
  ('flying','swan','Cisne','Swan','suán',6),
  ('flying','seagull','Gaviota','Seagull','SÍ-gal',7),
  ('flying','dove','Paloma','Dove','dav',8),
  ('flying','flamingo','Flamenco','Flamingo','fla-MÍN-gou',9),
  ('flying','peacock','Pavo real','Peacock','PÍI-kok',10),
  ('flying','pelican','Pelícano','Pelican','PÉ-li-kan',11),
  ('flying','robin','Petirrojo','Robin','RÓ-bin',12),
  ('flying','stork','Cigüeña','Stork','stork',13),
  ('flying','toucan','Tucán','Toucan','TÚ-kan',14),
  ('flying','woodpecker','Pájaro carpintero','Woodpecker','UÚD-pe-ker',15),
  ('flying','cardinal','Cardenal','Cardinal','KÁR-di-nal',16),
  ('flying','crow','Cuervo','Crow','krou',17),
  ('flying','ostrich','Avestruz','Ostrich','ÓS-trich',18),
  ('flying','pigeon','Paloma','Pigeon','PÍ-llon',19),
  ('flying','sparrow','Gorrión','Sparrow','SPÉ-rou',20),
  ('bugs','bee','Abeja','Bee','bii',1),
  ('bugs','butterfly','Mariposa','Butterfly','BÁ-ter-flai',2),
  ('bugs','ant','Hormiga','Ant','ant',3),
  ('bugs','ladybug','Mariquita','Ladybug','LÉI-di-bag',4),
  ('bugs','beetle','Escarabajo','Beetle','BÍ-tel',5),
  ('bugs','spider','Araña','Spider','SPÁI-der',6),
  ('bugs','snail','Caracol','Snail','snéil',7),
  ('bugs','centipede','Ciempiés','Centipede','SÉN-ti-piid',8),
  ('bugs','cricket','Grillo','Cricket','KRÍ-ket',9),
  ('bugs','dragonfly','Libélula','Dragonfly','DRÁ-gon-flai',10),
  ('bugs','firefly','Luciérnaga','Firefly','FÁIR-flai',11),
  ('bugs','grasshopper','Saltamontes','Grasshopper','GRÁS-jo-per',12),
  ('bugs','moth','Polilla','Moth','moz',13),
  ('bugs','wasp','Avispa','Wasp','uasp',14),
  ('bugs','worm','Gusano','Worm','uerm',15),
  ('bugs','caterpillar','Oruga','Caterpillar','KÁ-ter-pi-ler',16),
  ('bugs','fly','Mosca','Fly','flái',17),
  ('bugs','mosquito','Mosquito','Mosquito','mos-KÍ-tou',18),
  ('bugs','scorpion','Escorpión','Scorpion','SKÓR-pion',19),
  ('bugs','slug','Babosa','Slug','slag',20),
  ('dinosaurs','ankylosaurus','Anquilosaurio','Ankylosaurus','an-kai-lo-SÓR-us',1),
  ('dinosaurs','baby-dino','Bebé dino','Baby Dino','BÉI-bi DÁI-no',2),
  ('dinosaurs','brontosaurus','Brontosaurio','Brontosaurus','bron-to-SÓR-us',3),
  ('dinosaurs','dino-egg','Huevo de dino','Dino Egg','DÁI-no eg',4),
  ('dinosaurs','pterodactyl','Pterodáctilo','Pterodactyl','te-ro-DÁK-til',5),
  ('dinosaurs','raptor','Raptor','Raptor','RÁP-tor',6),
  ('dinosaurs','spinosaurus','Espinosaurio','Spinosaurus','spi-no-SÓR-us',7),
  ('dinosaurs','stegosaurus','Estegosaurio','Stegosaurus','ste-go-SÓR-us',8),
  ('dinosaurs','t-rex','Tiranosaurio','T-Rex','TI-reks',9),
  ('dinosaurs','triceratops','Triceratops','Triceratops','trai-SÉ-ra-tops',10),
  ('dinosaurs','allosaurus','Alosaurio','Allosaurus','a-lo-SÓR-us',11),
  ('dinosaurs','dilophosaurus','Dilofosaurio','Dilophosaurus','di-lo-fo-SÓR-us',12),
  ('dinosaurs','dino-skull','Cráneo de dino','Dino Skull','DÁI-no skal',13),
  ('dinosaurs','fossil','Fósil','Fossil','FÓ-sil',14),
  ('dinosaurs','pachycephalosaurus','Paquicefalosaurio','Pachycephalosaurus','pa-ki-se-fa-lo-SÓR-us',15),
  ('dinosaurs','parasaurolophus','Parasaurolofo','Parasaurolophus','pa-ra-so-RÓ-lo-fus',16),
  ('dinosaurs','diplodocus','Diplodocus','Diplodocus','di-PLÓ-do-kus',17),
  ('dinosaurs','iguanodon','Iguanodonte','Iguanodon','i-GUÁ-no-don',18),
  ('dinosaurs','plesiosaurus','Plesiosaurio','Plesiosaurus','ple-sio-SÓR-us',19),
  ('dinosaurs','volcano','Volcán','Volcano','vol-KÉI-nou',20),
  ('vehicles','airplane','Avión','Airplane','ÉR-plein',1),
  ('vehicles','bus','Autobús','Bus','bas',2),
  ('vehicles','car','Carro','Car','kar',3),
  ('vehicles','fire-truck','Camión de bomberos','Fire Truck','fáir trak',4),
  ('vehicles','helicopter','Helicóptero','Helicopter','JÉ-li-kop-ter',5),
  ('vehicles','police-car','Patrulla','Police Car','po-LÍS kar',6),
  ('vehicles','sailboat','Velero','Sailboat','SÉIL-bout',7),
  ('vehicles','tractor','Tractor','Tractor','TRÁK-tor',8),
  ('vehicles','train','Tren','Train','tréin',9),
  ('vehicles','truck','Camión','Truck','trak',10)
) as d(world_slug, slug, name_es, name_en, phonetic_es, sort_order)
join public.worlds w on w.slug = d.world_slug
on conflict (world_id, slug) do update set
  name_es = excluded.name_es, name_en = excluded.name_en,
  phonetic_es = excluded.phonetic_es, line_art_path = excluded.line_art_path,
  sort_order = excluded.sort_order, is_active = true;