insert into public.drawings (world_id, slug, name_es, name_en, phonetic_es, line_art_path, sort_order, is_active)
select w.id, d.slug, d.name_es, d.name_en, d.phonetic_es,
       'line-art/' || d.world_slug || '/' || d.slug || '.png', d.sort_order, true
from (values
  ('home','door','Puerta','Door','dor',5),
  ('home','fireplace','Chimenea','Fireplace','FÁIR-pleis',6),
  ('home','lamp','Lámpara','Lamp','lamp',7),
  ('home','mirror','Espejo','Mirror','MÍ-ror',8),
  ('home','pillow','Almohada','Pillow','PÍ-lou',9),
  ('home','rug','Tapete','Rug','rag',10),
  ('home','shelf','Estante','Shelf','shelf',11),
  ('home','sink','Lavabo','Sink','sink',12),
  ('home','sofa','Sofá','Sofa','SÓU-fa',13),
  ('home','stairs','Escaleras','Stairs','sters',14),
  ('home','table','Mesa','Table','TÉI-bel',15),
  ('home','window','Ventana','Window','UÍN-dou',16),
  ('home','blanket','Cobija','Blanket','BLÁN-ket',17),
  ('home','television','Televisión','Television','TÉ-le-vi-shon',18),
  ('home','toilet','Inodoro','Toilet','TÓI-let',19),
  ('home','wardrobe','Armario','Wardrobe','UÓR-droub',20),
  ('kitchen','bottle','Botella','Bottle','BÓ-tel',1),
  ('kitchen','bowl','Tazón','Bowl','boul',2),
  ('kitchen','cup','Taza','Cup','kap',3),
  ('kitchen','fork','Tenedor','Fork','fork',4),
  ('kitchen','knife','Cuchillo','Knife','náif',5),
  ('kitchen','napkin','Servilleta','Napkin','NÁP-kin',6),
  ('kitchen','pan','Sartén','Pan','pan',7),
  ('kitchen','pot','Olla','Pot','pot',8),
  ('kitchen','refrigerator','Refrigerador','Refrigerator','ri-FRÍ-lle-rei-tor',9),
  ('kitchen','spoon','Cuchara','Spoon','spun',10),
  ('kitchen','stove','Estufa','Stove','stouv',11),
  ('kitchen','teapot','Tetera','Teapot','TÍI-pot',12),
  ('kitchen','blender','Licuadora','Blender','BLÉN-der',13),
  ('kitchen','glass','Vaso','Glass','glas',14),
  ('kitchen','jar','Frasco','Jar','llar',15),
  ('kitchen','kettle','Hervidor','Kettle','KÉ-tel',16),
  ('kitchen','mug','Tarro','Mug','mag',17),
  ('kitchen','oven','Horno','Oven','Á-ven',18),
  ('kitchen','plate','Plato','Plate','pléit',19),
  ('kitchen','toaster','Tostadora','Toaster','TÓUS-ter',20),
  ('toys','board-game','Juego de mesa','Board Game','bord géim',1),
  ('toys','building-blocks','Bloques','Building Blocks','BÍL-ding bloks',2),
  ('toys','doll','Muñeca','Doll','dol',3),
  ('toys','dollhouse','Casa de muñecas','Dollhouse','DÓL-jaus',4),
  ('toys','marbles','Canicas','Marbles','MÁR-bels',5),
  ('toys','rocking-horse','Caballito','Rocking Horse','RÓ-king jors',6),
  ('toys','spinning-top','Trompo','Spinning Top','SPÍ-ning top',7),
  ('toys','teddy-bear','Osito de peluche','Teddy Bear','TÉ-di ber',8),
  ('toys','ball','Pelota','Ball','bol',9),
  ('toys','bubbles','Burbujas','Bubbles','BÁ-bels',10),
  ('toys','jack-in-the-box','Caja sorpresa','Jack-in-the-box','llak-in-de-BÓKS',11),
  ('toys','kaleidoscope','Caleidoscopio','Kaleidoscope','ka-LÁI-dos-koup',12),
  ('toys','play-dough','Plastilina','Play Dough','pléi dou',13),
  ('toys','puzzle','Rompecabezas','Puzzle','PÁ-sel',14),
  ('toys','rattle','Sonaja','Rattle','RÁ-tel',15),
  ('toys','slinky','Resorte','Slinky','SLÍN-ki',16),
  ('toys','toy-robot','Robot de juguete','Toy Robot','toi RÓU-bot',17),
  ('toys','toy-soldier','Soldadito','Toy Soldier','toi SÓUL-ller',18),
  ('toys','wagon','Carrito','Wagon','UÁ-gon',19),
  ('toys','yo-yo','Yoyo','Yo-Yo','IÓU-iou',20),
  ('school','backpack','Mochila','Backpack','BÁK-pak',1),
  ('school','desk','Pupitre','Desk','desk',2),
  ('school','globe','Globo terráqueo','Globe','gloub',3),
  ('school','glue','Pegamento','Glue','glu',4),
  ('school','marker','Marcador','Marker','MÁR-ker',5),
  ('school','notebook','Cuaderno','Notebook','NÓUT-buk',6),
  ('school','paint','Pintura','Paint','péint',7),
  ('school','paper','Papel','Paper','PÉI-per',8),
  ('school','ruler','Regla','Ruler','RÚ-ler',9),
  ('school','scissors','Tijeras','Scissors','SÍ-sors',10),
  ('school','book','Libro','Book','buk',11),
  ('school','calculator','Calculadora','Calculator','KÁL-kiu-lei-tor',12),
  ('school','chalk','Gis','Chalk','chok',13),
  ('school','chalkboard','Pizarrón','Chalkboard','CHÓK-bord',14),
  ('school','crayon','Crayón','Crayon','KRÉI-on',15),
  ('school','eraser','Goma de borrar','Eraser','i-RÉI-ser',16),
  ('school','paintbrush','Pincel','Paintbrush','PÉINT-brash',17),
  ('school','pencil','Lápiz','Pencil','PÉN-sil',18),
  ('school','pencil-case','Estuche','Pencil Case','PÉN-sil kéis',19),
  ('school','stapler','Engrapadora','Stapler','STÉI-pler',20),
  ('nature','bush','Arbusto','Bush','bush',1),
  ('nature','cave','Cueva','Cave','kéiv',2),
  ('nature','flower','Flor','Flower','FLÁU-er',3),
  ('nature','grass','Pasto','Grass','gras',4),
  ('nature','hill','Colina','Hill','jil',5),
  ('nature','lake','Lago','Lake','léik',6),
  ('nature','pinecone','Piña de pino','Pinecone','PÁIN-koun',7),
  ('nature','pond','Estanque','Pond','pond',8),
  ('nature','river','Río','River','RÍ-ver',9),
  ('nature','tree','Árbol','Tree','trii',10),
  ('nature','waterfall','Cascada','Waterfall','UÓ-ter-fol',11),
  ('nature','acorn','Bellota','Acorn','ÉI-korn',12),
  ('nature','cactus','Cactus','Cactus','KÁK-tus',13),
  ('nature','island','Isla','Island','ÁI-land',14),
  ('nature','leaf','Hoja','Leaf','liif',15),
  ('nature','log','Tronco','Log','log',16),
  ('nature','mountain','Montaña','Mountain','MÁUN-tin',17),
  ('nature','rock','Roca','Rock','rok',18),
  ('nature','seed','Semilla','Seed','siid',19),
  ('nature','sprout','Brote','Sprout','spraut',20),
  ('weather','puddle','Charco','Puddle','PÁ-del',1),
  ('weather','tornado','Tornado','Tornado','tor-NÉI-dou',2),
  ('weather','umbrella','Paraguas','Umbrella','am-BRÉ-la',3),
  ('weather','wind','Viento','Wind','uind',4),
  ('weather','cloud','Nube','Cloud','klaud',5),
  ('weather','fog','Niebla','Fog','fog',6),
  ('weather','hail','Granizo','Hail','jéil',7),
  ('weather','icicle','Carámbano','Icicle','ÁI-si-kel',8),
  ('weather','lightning','Rayo','Lightning','LÁIT-ning',9),
  ('weather','rain','Lluvia','Rain','réin',10),
  ('weather','rainbow','Arcoíris','Rainbow','RÉIN-bou',11),
  ('weather','snow','Nieve','Snow','snou',12),
  ('weather','snowflake','Copo de nieve','Snowflake','SNÓU-fleik',13),
  ('weather','storm','Tormenta','Storm','storm',14),
  ('city','bus-stop','Parada de autobús','Bus Stop','bas stop',1),
  ('city','gas-station','Gasolinera','Gas Station','gas STÉI-shon',2),
  ('city','house','Casa','House','jaus',3),
  ('city','library','Biblioteca','Library','LÁI-bre-ri',4),
  ('city','park','Parque','Park','park',5),
  ('city','playground','Parque de juegos','Playground','PLÉI-graund',6),
  ('city','police-station','Estación de policía','Police Station','po-LÍS STÉI-shon',7),
  ('city','post-office','Oficina de correos','Post Office','poust Ó-fis',8),
  ('city','store','Tienda','Store','stor',9),
  ('city','bakery','Panadería','Bakery','BÉI-ke-ri',10),
  ('city','bridge','Puente','Bridge','brill',11),
  ('city','fire-station','Estación de bomberos','Fire Station','fáir STÉI-shon',12),
  ('city','hospital','Hospital','Hospital','JÓS-pi-tal',13),
  ('city','restaurant','Restaurante','Restaurant','RÉS-to-rant',14),
  ('city','school-building','Escuela','School Building','skul BÍL-ding',15),
  ('city','skyscraper','Rascacielos','Skyscraper','SKÁI-skrei-per',16),
  ('city','traffic-light','Semáforo','Traffic Light','TRÁ-fik lait',17),
  ('city','zoo','Zoológico','Zoo','zuu',18),
  ('tools','drill','Taladro','Drill','dril',1),
  ('tools','level','Nivel','Level','LÉ-vel',2),
  ('tools','pliers','Pinzas','Pliers','PLÁI-ers',3),
  ('tools','rake','Rastrillo','Rake','réik',4),
  ('tools','saw','Serrucho','Saw','so',5),
  ('tools','screw','Tornillo','Screw','skru',6),
  ('tools','tape-measure','Cinta métrica','Tape Measure','téip MÉ-sher',7),
  ('tools','bolt','Perno','Bolt','boult',8),
  ('tools','hammer','Martillo','Hammer','JÁ-mer',9),
  ('tools','ladder','Escalera','Ladder','LÁ-der',10),
  ('tools','nail','Clavo','Nail','néil',11),
  ('tools','paint-roller','Rodillo','Paint Roller','péint RÓU-ler',12),
  ('tools','screwdriver','Desarmador','Screwdriver','SKRÚ-drai-ver',13),
  ('tools','shovel','Pala','Shovel','SHÁ-vel',14),
  ('tools','toolbox','Caja de herramientas','Toolbox','TÚL-boks',15),
  ('tools','wrench','Llave','Wrench','rench',16)
) as d(world_slug, slug, name_es, name_en, phonetic_es, sort_order)
join public.worlds w on w.slug = d.world_slug
on conflict (world_id, slug) do update set
  name_es = excluded.name_es, name_en = excluded.name_en,
  phonetic_es = excluded.phonetic_es, line_art_path = excluded.line_art_path,
  sort_order = excluded.sort_order, is_active = true;